<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250922212105 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql("CREATE TYPE coupon_type AS ENUM ('percentage', 'fixed')");
        $this->addSql("CREATE TYPE currency AS ENUM ('USD', 'EUR')");
        $this->addSql("CREATE TYPE purchases_status AS ENUM ('pending', 'paid', 'failed', 'refunded')");

        $this->addSql('CREATE TABLE coupons (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(64) NOT NULL, type coupon_type, value NUMERIC(10, 2) NOT NULL, valid_from TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, valid_to TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F564111877153098 ON coupons (code)');
        $this->addSql('CREATE TABLE payments (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider VARCHAR(32) NOT NULL, provider_ref VARCHAR(128) NOT NULL, amount NUMERIC(10, 2) NOT NULL, currency currency, status VARCHAR(32) NOT NULL, error_message TEXT DEFAULT NULL, request_body TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, purchase_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_65D29B32558FBEB9 ON payments (purchase_id)');
        $this->addSql('CREATE TABLE products (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, price NUMERIC(10, 2) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B3BA5A5A5E237E06 ON products (name)');
        $this->addSql('CREATE TABLE purchase_idempotency_keys (key VARCHAR(128) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, purchase_id BIGINT DEFAULT NULL, PRIMARY KEY (key))');
        $this->addSql('CREATE INDEX IDX_220D4ADB558FBEB9 ON purchase_idempotency_keys (purchase_id)');
        $this->addSql('CREATE INDEX idx_pik_created_at ON purchase_idempotency_keys (created_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_pik_purchase_id ON purchase_idempotency_keys (purchase_id, key)');
        $this->addSql('CREATE TABLE purchases (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tax_number VARCHAR(64) NOT NULL, country VARCHAR(4) NOT NULL, coupon_code VARCHAR(64) DEFAULT NULL, total_net_amount NUMERIC(10, 2) NOT NULL, subtotal_net NUMERIC(10, 2) NOT NULL, tax_amount NUMERIC(10, 2) NOT NULL, total_amount NUMERIC(10, 2) NOT NULL, currency currency, status purchases_status, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tax_rates (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, country VARCHAR(4) NOT NULL, rate NUMERIC(5, 4) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_tax_rates_country ON tax_rates (country)');
        $this->addSql('ALTER TABLE payments ADD CONSTRAINT FK_65D29B32558FBEB9 FOREIGN KEY (purchase_id) REFERENCES purchases (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_idempotency_keys ADD CONSTRAINT FK_220D4ADB558FBEB9 FOREIGN KEY (purchase_id) REFERENCES purchases (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE payments DROP CONSTRAINT FK_65D29B32558FBEB9');
        $this->addSql('ALTER TABLE purchase_idempotency_keys DROP CONSTRAINT FK_220D4ADB558FBEB9');
        $this->addSql('DROP TABLE coupons');
        $this->addSql('DROP TABLE payments');
        $this->addSql('DROP TABLE products');
        $this->addSql('DROP TABLE purchase_idempotency_keys');
        $this->addSql('DROP TABLE purchases');
        $this->addSql('DROP TABLE tax_rates');
    }
}
